# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - image-search-engine

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2c63cd0f8326418db1aa7eb1a17e19aa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7bf857deb6ab4c039a9581ac45e76936 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2c63cd0f8326418db1aa7eb1a17e19aa }}/subomiodekunle/image-search:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'image-search-engine'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d116f7c9cf274014beda3c452cbda2b0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2c63cd0f8326418db1aa7eb1a17e19aa }}/subomiodekunle/image-search:${{ github.sha }}'